version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # Map port 5000 of the container to port 5000 of the host
    depends_on:
      - db
      - redis
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb

  redis:
    image: redis:6
    ports:
      - "6379:6379"
